<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "profilematching"
 *
 * Auto generated by Extension Builder 2018-01-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Profile_Matching',
    'description' => 'Matching users profile based on user\'s interest.',
    'category' => 'plugin',
    'author' => 'Hrushikesh Sakunde',
    'author_email' => 'sakundehrushi@gmail.com',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
